// <auto-generated />
namespace GlobalTVBilling.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _2_08122014 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2_08122014));
        
        string IMigrationMetadata.Id
        {
            get { return "201412081320163_2_08122014"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
