//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalTVBilling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class st_Customers
    {
        public int ID { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string PersonalNo { get; set; }
        public string Address { get; set; }
        public long CardNo { get; set; }
        public string Phone { get; set; }
        public string CarNo { get; set; }
        public System.DateTime ActiveDate { get; set; }
        public decimal Balance { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsInBilling { get; set; }
        public Nullable<bool> IsRegistered { get; set; }
        public bool IsDisabled { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Send_Status { get; set; }
        public Nullable<bool> Before_ActiveDate_Send { get; set; }
        public Nullable<bool> After_ActiveDate_Send { get; set; }
    }
}
